ftp_root: /Users/igla/Desktop/gg-incoming
archive_base_path: /Volumes/ARCHIVE1/archive1
prep_base_path: /Users/igla/Desktop/_script_workflow/prep
ready_base_path: /Users/igla/Desktop/_script_workflow/ready